//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aaalog
    {
        public int id { get; set; }
        public string tablename { get; set; }
        public string des { get; set; }
        public string sqlx { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
