//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_congno_dauky
    {
        public int so_coso { get; set; }
        public int so_donvi { get; set; }
        public decimal so_namhoc { get; set; }
        public decimal so_khoi { get; set; }
        public int so_hocsinh { get; set; }
        public decimal so_lophoc { get; set; }
        public string hocphan { get; set; }
        public Nullable<decimal> dkno_hp { get; set; }
        public Nullable<decimal> dkco_hp { get; set; }
        public Nullable<decimal> ckno_hp { get; set; }
        public Nullable<decimal> ckco_hp { get; set; }
        public Nullable<decimal> dkno_an { get; set; }
        public Nullable<decimal> dkco_an { get; set; }
        public Nullable<decimal> ckno_an { get; set; }
        public Nullable<decimal> ckco_an { get; set; }
        public Nullable<decimal> dkno_xt { get; set; }
        public Nullable<decimal> dkco_xt { get; set; }
        public Nullable<decimal> ckno_xt { get; set; }
        public Nullable<decimal> ckco_xt { get; set; }
        public Nullable<decimal> dkno_gc { get; set; }
        public Nullable<decimal> dkco_gc { get; set; }
        public Nullable<decimal> ckno_gc { get; set; }
        public Nullable<decimal> ckco_gc { get; set; }
        public Nullable<decimal> dkno_nh { get; set; }
        public Nullable<decimal> dkco_nh { get; set; }
        public Nullable<decimal> ckno_nh { get; set; }
        public Nullable<decimal> ckco_nh { get; set; }
        public Nullable<decimal> dkno_dp { get; set; }
        public Nullable<decimal> dkco_dp { get; set; }
        public Nullable<decimal> ckno_dp { get; set; }
        public Nullable<decimal> ckco_dp { get; set; }
        public Nullable<decimal> dkno_nt { get; set; }
        public Nullable<decimal> dkco_nt { get; set; }
        public Nullable<decimal> ckno_nt { get; set; }
        public Nullable<decimal> ckco_nt { get; set; }
        public Nullable<decimal> dkno_xe { get; set; }
        public Nullable<decimal> dkco_xe { get; set; }
        public Nullable<decimal> ckno_xe { get; set; }
        public Nullable<decimal> ckco_xe { get; set; }
        public Nullable<decimal> dkno_sa { get; set; }
        public Nullable<decimal> dkco_sa { get; set; }
        public Nullable<decimal> ckno_sa { get; set; }
        public Nullable<decimal> ckco_sa { get; set; }
        public Nullable<decimal> dkno_bh { get; set; }
        public Nullable<decimal> dkco_bh { get; set; }
        public Nullable<decimal> ckno_bh { get; set; }
        public Nullable<decimal> ckco_bh { get; set; }
        public Nullable<decimal> dkno_kh { get; set; }
        public Nullable<decimal> dkco_kh { get; set; }
        public Nullable<decimal> ckno_kh { get; set; }
        public Nullable<decimal> ckco_kh { get; set; }
        public Nullable<decimal> sodudkco { get; set; }
        public Nullable<decimal> sodudkno { get; set; }
        public Nullable<decimal> psno { get; set; }
        public Nullable<decimal> psco { get; set; }
        public Nullable<decimal> tongno { get; set; }
        public Nullable<decimal> tongco { get; set; }
        public Nullable<decimal> soduckco { get; set; }
        public Nullable<decimal> soduckno { get; set; }
        public string ghichu { get; set; }
        public string ma_user { get; set; }
        public System.DateTime edate { get; set; }
    }
}
