//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_lop_kqht
    {
        public decimal so { get; set; }
        public Nullable<int> so_hv { get; set; }
        public Nullable<decimal> so_namhoc_lop { get; set; }
        public string hocky { get; set; }
        public Nullable<decimal> toan { get; set; }
        public Nullable<decimal> ly { get; set; }
        public Nullable<decimal> hoa { get; set; }
        public Nullable<decimal> sinh { get; set; }
        public Nullable<decimal> tinhoc { get; set; }
        public Nullable<decimal> nguvan { get; set; }
        public Nullable<decimal> su { get; set; }
        public Nullable<decimal> dia { get; set; }
        public Nullable<decimal> nngu { get; set; }
        public Nullable<decimal> gdcd { get; set; }
        public Nullable<decimal> conghe { get; set; }
        public string theduc { get; set; }
        public string amnhac { get; set; }
        public string mythuat { get; set; }
        public string thucong { get; set; }
        public string daoduc { get; set; }
        public Nullable<decimal> tunhien { get; set; }
        public Nullable<decimal> khoahoc { get; set; }
        public Nullable<decimal> sudia { get; set; }
        public Nullable<decimal> qphong { get; set; }
        public Nullable<decimal> nghept { get; set; }
        public Nullable<decimal> tbcm { get; set; }
        public string hocluc { get; set; }
        public string hanhkiem { get; set; }
        public string danhhieu { get; set; }
        public string ma_users { get; set; }
        public string ghichu { get; set; }
        public System.DateTime mdate { get; set; }
    }
}
