//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_khieunai
    {
        public int so { get; set; }
        public Nullable<int> so_hv { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string truong { get; set; }
        public string lop { get; set; }
        public string phanloai { get; set; }
        public string nguoikhieunai { get; set; }
        public string quanhevoihs { get; set; }
        public string noidung { get; set; }
        public string tieude { get; set; }
        public string noixuly { get; set; }
        public string ketquaxuly { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> ngayphucdap { get; set; }
        public string phuongthucphanhoi { get; set; }
    }
}
