//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_lop_cackhoanthu_log
    {
        public decimal so { get; set; }
        public int so_hocsinh_lop { get; set; }
        public string loai { get; set; }
        public int so_khoanthu { get; set; }
        public int so_khoanthuct { get; set; }
        public string cachtinh { get; set; }
        public string machiphi { get; set; }
        public string noidungthu { get; set; }
        public Nullable<decimal> phantramgiam { get; set; }
        public string lydogiam { get; set; }
        public Nullable<decimal> phantramgiam1 { get; set; }
        public string phantramgiam1text { get; set; }
        public Nullable<decimal> phantramgiam2 { get; set; }
        public string phantramgiam2text { get; set; }
        public Nullable<decimal> phantramgiam3 { get; set; }
        public string phantramgiam3text { get; set; }
        public Nullable<decimal> sotien { get; set; }
        public Nullable<decimal> giamtru { get; set; }
        public string giamtrutext { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> hanthanhtoan { get; set; }
        public System.DateTime cdate { get; set; }
        public string userid { get; set; }
    }
}
