//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_namhoc_lop
    {
        public int so { get; set; }
        public decimal so_lop { get; set; }
        public decimal so_namhoc { get; set; }
        public int so_donvi { get; set; }
        public string giaovien { get; set; }
        public Nullable<decimal> hocphi { get; set; }
        public Nullable<decimal> phantramchietkhau { get; set; }
        public string cahoc { get; set; }
        public string phonghoc { get; set; }
        public string thoigianhoc { get; set; }
        public Nullable<System.DateTime> ngaybatdau { get; set; }
        public Nullable<System.DateTime> ngayketthuc { get; set; }
        public string giaotrinh { get; set; }
        public string CD { get; set; }
        public string ghichu { get; set; }
    }
}
