//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_cackhoanthu_chitiet
    {
        public int so { get; set; }
        public int so_khoanthu { get; set; }
        public decimal so_khoi { get; set; }
        public int so_hedaotao { get; set; }
        public string hocphan { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public decimal sotien { get; set; }
        public decimal sotien2 { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
        public Nullable<System.DateTime> thoihan { get; set; }
        public string ghichu { get; set; }
        public bool sudung { get; set; }
        public string ma_khoanthu { get; set; }
    }
}
