//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_kehoachdaotao
    {
        public decimal so { get; set; }
        public int so_hedaotao { get; set; }
        public int so_monhoc { get; set; }
        public int so_namhoc { get; set; }
        public decimal heso { get; set; }
        public bool monthi { get; set; }
        public bool montn { get; set; }
        public int loaimonhoc { get; set; }
        public string ghichu { get; set; }
        public string sortorder { get; set; }
    }
}
