//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_lop
    {
        public int so { get; set; }
        public int so_donvi { get; set; }
        public int so_hv { get; set; }
        public int so_namhoc_lop { get; set; }
        public Nullable<decimal> so_namhoc { get; set; }
        public Nullable<int> so_khoi { get; set; }
        public Nullable<decimal> so_lophoc { get; set; }
        public string loai { get; set; }
        public Nullable<decimal> hp { get; set; }
        public Nullable<decimal> giamtru { get; set; }
        public string giamtrutext { get; set; }
        public Nullable<decimal> ptck { get; set; }
        public string lydock { get; set; }
        public Nullable<decimal> ptck1 { get; set; }
        public string lydock1 { get; set; }
        public Nullable<decimal> ptck2 { get; set; }
        public string lydock2 { get; set; }
        public Nullable<decimal> ptck3 { get; set; }
        public string lydock3 { get; set; }
        public Nullable<decimal> ptck4 { get; set; }
        public string lydock4 { get; set; }
        public Nullable<decimal> diem1 { get; set; }
        public Nullable<decimal> diem2 { get; set; }
        public Nullable<decimal> diem3 { get; set; }
        public Nullable<decimal> diem4 { get; set; }
        public Nullable<decimal> dtb { get; set; }
        public Nullable<bool> Thu_T01 { get; set; }
        public string NoidungThu_t01 { get; set; }
        public Nullable<bool> Thu_T02 { get; set; }
        public string NoidungThu_t02 { get; set; }
        public Nullable<bool> Thu_T03 { get; set; }
        public string NoidungThu_t03 { get; set; }
        public Nullable<bool> Thu_T04 { get; set; }
        public string NoidungThu_t04 { get; set; }
        public Nullable<bool> Thu_T05 { get; set; }
        public string NoidungThu_t05 { get; set; }
        public Nullable<bool> Thu_T06 { get; set; }
        public string NoidungThu_t06 { get; set; }
        public Nullable<bool> Thu_T07 { get; set; }
        public string NoidungThu_t07 { get; set; }
        public Nullable<bool> Thu_T08 { get; set; }
        public string NoidungThu_t08 { get; set; }
        public Nullable<bool> Thu_T09 { get; set; }
        public string NoidungThu_t09 { get; set; }
        public Nullable<bool> Thu_T10 { get; set; }
        public string NoidungThu_t10 { get; set; }
        public Nullable<bool> Thu_T11 { get; set; }
        public string NoidungThu_t11 { get; set; }
        public string NoidungThu_t12 { get; set; }
        public Nullable<bool> Thu_T12 { get; set; }
        public string noikcb { get; set; }
        public Nullable<System.DateTime> ngayvaolop { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<System.DateTime> trangthaingay { get; set; }
        public string trangthailydo { get; set; }
        public string ghichu { get; set; }
        public string ghichuta { get; set; }
        public string nopdondknhaphoc { get; set; }
        public string nopthongtinhs { get; set; }
        public string nopgiaycnhoanthanhcuoicap { get; set; }
        public string nopgcnchuyentruong { get; set; }
        public string nophocba { get; set; }
        public string nopgiaykhaisinh { get; set; }
        public string nopsohokhau { get; set; }
        public string nopphieukhamsuckhoe { get; set; }
        public string nophinhanh { get; set; }
        public string nopkhac { get; set; }
        public Nullable<int> solh { get; set; }
        public bool dong1nam { get; set; }
        public bool dongta1nam { get; set; }
        public bool dongnt1nam { get; set; }
        public bool dongxe1nam { get; set; }
        public string stt { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string userid { get; set; }
    }
}
