//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_congno
    {
        public decimal so { get; set; }
        public Nullable<int> so_hocsinh_lop { get; set; }
        public int so_donvi { get; set; }
        public int thang { get; set; }
        public int nam { get; set; }
        public int so_hocsinh { get; set; }
        public decimal so_namhoc { get; set; }
        public int so_khoi { get; set; }
        public string hocphan { get; set; }
        public Nullable<int> so_lophoc { get; set; }
        public decimal conghile { get; set; }
        public string conghiletext { get; set; }
        public decimal conghiphep { get; set; }
        public string conghipheptext { get; set; }
        public decimal cocantru { get; set; }
        public string cocantrutext { get; set; }
        public decimal cocantru1 { get; set; }
        public string cocantru1text { get; set; }
        public decimal cocantru2 { get; set; }
        public string cocantru2text { get; set; }
        public decimal cocantru3 { get; set; }
        public string cocantru3text { get; set; }
        public decimal cocantru4 { get; set; }
        public string cocantru4text { get; set; }
        public decimal cocantru5 { get; set; }
        public string cocantru5text { get; set; }
        public decimal cocantru6 { get; set; }
        public string cocantru6text { get; set; }
        public decimal cocantru7 { get; set; }
        public string cocantru7text { get; set; }
        public decimal cocantru8 { get; set; }
        public string cocantru8text { get; set; }
        public decimal cocantru9 { get; set; }
        public string cocantru9text { get; set; }
        public decimal cocantru0 { get; set; }
        public string cocantru0text { get; set; }
        public decimal cocantrul { get; set; }
        public string cocantrultext { get; set; }
        public Nullable<decimal> nophaithu { get; set; }
        public string nophaithutext { get; set; }
        public Nullable<decimal> nophaithu1 { get; set; }
        public string nophaithu1text { get; set; }
        public Nullable<decimal> nophaithu2 { get; set; }
        public string nophaithu2text { get; set; }
        public Nullable<decimal> nophaithu3 { get; set; }
        public string nophaithu3text { get; set; }
        public Nullable<decimal> nophaithu4 { get; set; }
        public string nophaithu4text { get; set; }
        public Nullable<decimal> nophaithu5 { get; set; }
        public string nophaithu5text { get; set; }
        public Nullable<decimal> nophaithu6 { get; set; }
        public string nophaithu6text { get; set; }
        public Nullable<decimal> nophaithu7 { get; set; }
        public string nophaithu7text { get; set; }
        public Nullable<decimal> nophaithu8 { get; set; }
        public string nophaithu8text { get; set; }
        public Nullable<decimal> nophaithu9 { get; set; }
        public string nophaithu9text { get; set; }
        public Nullable<decimal> nophaithu0 { get; set; }
        public string nophaithu0text { get; set; }
        public Nullable<decimal> nophaithul { get; set; }
        public string nophaithultext { get; set; }
        public decimal sodudkno { get; set; }
        public decimal sodudkco { get; set; }
        public string noidungsms { get; set; }
        public string ghichu { get; set; }
        public bool khoa { get; set; }
        public System.DateTime cdate { get; set; }
    }
}
