//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_lophoc
    {
        public decimal SO { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public Nullable<decimal> SO_HE { get; set; }
        public string KHOI { get; set; }
        public string STT { get; set; }
        public Nullable<decimal> HP { get; set; }
        public Nullable<decimal> PTCK { get; set; }
        public string TENGV { get; set; }
        public string GIAOTRINH { get; set; }
        public string CDROM { get; set; }
        public string PHONGHOC { get; set; }
        public string THOIGIANHOC { get; set; }
        public Nullable<System.DateTime> SDATE { get; set; }
        public Nullable<System.DateTime> EDATE { get; set; }
        public Nullable<int> LOAI { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> SUDUNG { get; set; }
    }
}
