//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_update
    {
        public int so { get; set; }
        public string ma { get; set; }
        public string ma_new { get; set; }
        public string ma2 { get; set; }
        public string ma2_new { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public string hoten { get; set; }
        public string hoten_new { get; set; }
        public string hodem { get; set; }
        public string hodem_new { get; set; }
        public string ten { get; set; }
        public string ten_new { get; set; }
        public string Quoctich { get; set; }
        public string Quoctich_new { get; set; }
        public Nullable<System.DateTime> sinhnhat { get; set; }
        public Nullable<System.DateTime> sinhnhat_new { get; set; }
        public string noisinh { get; set; }
        public string noisinh_new { get; set; }
        public Nullable<System.DateTime> ngaynhaphoc { get; set; }
        public Nullable<System.DateTime> ngaynhaphoc_new { get; set; }
        public string phai { get; set; }
        public string phai_new { get; set; }
        public string dantoc { get; set; }
        public string dantoc_new { get; set; }
        public string email { get; set; }
        public string email_new { get; set; }
        public string diachi { get; set; }
        public string diachi_new { get; set; }
        public string quan { get; set; }
        public string quan_new { get; set; }
        public string thanhpho { get; set; }
        public string thanhpho_new { get; set; }
        public string cmnd { get; set; }
        public string cmnd_new { get; set; }
        public string dienthoai { get; set; }
        public string dienthoai_new { get; set; }
        public string hktt { get; set; }
        public string hktt_new { get; set; }
        public string nhan_vien_tiep_thi { get; set; }
        public string nhan_vien_tiep_thi_new { get; set; }
        public string cha_hoten { get; set; }
        public string cha_hoten_new { get; set; }
        public string cha_dienthoai { get; set; }
        public string cha_dienthoai_new { get; set; }
        public string me_hoten { get; set; }
        public string me_hoten_new { get; set; }
        public string me_dienthoai { get; set; }
        public string me_dienthoai_new { get; set; }
        public string tinhtrang { get; set; }
        public string tinhtrang_new { get; set; }
        public Nullable<System.DateTime> tinhtrang_ngay { get; set; }
        public Nullable<System.DateTime> tinhtrang_ngay_new { get; set; }
        public string tinhtrang_lydo { get; set; }
        public string tinhtrang_lydo_new { get; set; }
        public string ghichu { get; set; }
        public string ghichu_new { get; set; }
        public string khoi { get; set; }
        public string khoi_new { get; set; }
        public Nullable<int> so_donvi { get; set; }
        public Nullable<int> so_donvi_new { get; set; }
        public string userid { get; set; }
        public string userid_new { get; set; }
        public System.DateTime CDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public int chinhsach { get; set; }
        public int chinhsach_new { get; set; }
        public string hoten_cs { get; set; }
        public string hoten_cs_new { get; set; }
        public string quanhe_cs { get; set; }
        public string quanhe_cs_new { get; set; }
    }
}
