//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocphi_namhoc_khoi_thang
    {
        public int so { get; set; }
        public decimal so_namhoc { get; set; }
        public int so_coso { get; set; }
        public decimal so_khoi { get; set; }
        public string hocphan { get; set; }
        public string loai { get; set; }
        public decimal sotien { get; set; }
        public decimal hocphigoc { get; set; }
        public decimal C { get; set; }
        public decimal M { get; set; }
        public Nullable<decimal> PHAU { get; set; }
        public Nullable<decimal> PHNH { get; set; }
        public Nullable<decimal> PHXT { get; set; }
        public Nullable<decimal> BHYT { get; set; }
        public Nullable<decimal> SABH { get; set; }
        public Nullable<decimal> PHGC { get; set; }
        public Nullable<decimal> PHDP { get; set; }
        public Nullable<decimal> PHNT { get; set; }
        public Nullable<decimal> PHKH { get; set; }
        public Nullable<decimal> PHDD { get; set; }
        public Nullable<decimal> YOGA { get; set; }
        public string dvt { get; set; }
        public string noidung { get; set; }
        public string ghichu { get; set; }
    }
}
