//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_thoikhoabieu
    {
        public int so { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> so_namhoc_lop { get; set; }
        public Nullable<int> so_tkb { get; set; }
        public string buoi { get; set; }
        public Nullable<int> so_phong { get; set; }
        public string phonghoc { get; set; }
        public string tiet { get; set; }
        public string thoigian { get; set; }
        public Nullable<int> Thu_2_mon_so { get; set; }
        public string Thu_2_mon { get; set; }
        public Nullable<int> Thu_2_GV_so { get; set; }
        public string Thu_2_GV { get; set; }
        public Nullable<int> Thu_2_phong_so { get; set; }
        public Nullable<int> Thu_3_mon_so { get; set; }
        public string Thu_3_mon { get; set; }
        public Nullable<int> Thu_3_gv_so { get; set; }
        public string Thu_3_gv { get; set; }
        public Nullable<int> Thu_3_phong_so { get; set; }
        public Nullable<int> Thu_4_mon_so { get; set; }
        public string Thu_4_mon { get; set; }
        public Nullable<int> Thu_4_gv_so { get; set; }
        public string Thu_4_gv { get; set; }
        public Nullable<int> Thu_4_phong_so { get; set; }
        public Nullable<int> Thu_5_mon_so { get; set; }
        public string Thu_5_mon { get; set; }
        public Nullable<int> Thu_5_gv_so { get; set; }
        public string Thu_5_gv { get; set; }
        public Nullable<int> Thu_5_phong_so { get; set; }
        public Nullable<int> Thu_6_mon_so { get; set; }
        public string Thu_6_mon { get; set; }
        public Nullable<int> Thu_6_gv_so { get; set; }
        public string Thu_6_gv { get; set; }
        public Nullable<int> Thu_6_phong_so { get; set; }
        public Nullable<int> Thu_7_mon_so { get; set; }
        public string Thu_7_mon { get; set; }
        public Nullable<int> Thu_7_gv_so { get; set; }
        public string Thu_7_gv { get; set; }
        public Nullable<int> Thu_7_phong_so { get; set; }
    }
}
