//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_cackhoanthumau
    {
        public int so { get; set; }
        public Nullable<decimal> so_namhoc { get; set; }
        public string machiphi { get; set; }
        public string noidungthu { get; set; }
        public Nullable<decimal> sotien { get; set; }
        public Nullable<System.DateTime> hanthanhtoan { get; set; }
        public string ma_vth { get; set; }
        public bool dangthu { get; set; }
    }
}
