//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_phieuthu_ct
    {
        public decimal so { get; set; }
        public int so_donvi { get; set; }
        public decimal so_phieuxuat { get; set; }
        public decimal so_phieuthu { get; set; }
        public decimal sotien { get; set; }
        public string ghichu { get; set; }
    }
}
