//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_lop_diemdanhthang
    {
        public int so { get; set; }
        public Nullable<int> so_hocsinh_lop { get; set; }
        public Nullable<int> thang { get; set; }
        public Nullable<int> nam { get; set; }
        public string N00 { get; set; }
        public string N01 { get; set; }
        public string N02 { get; set; }
        public string N03 { get; set; }
        public string N04 { get; set; }
        public string N05 { get; set; }
        public string N06 { get; set; }
        public string N07 { get; set; }
        public string N08 { get; set; }
        public string N09 { get; set; }
        public string N10 { get; set; }
        public string N11 { get; set; }
        public string N12 { get; set; }
        public string N13 { get; set; }
        public string N14 { get; set; }
        public string N15 { get; set; }
        public string N16 { get; set; }
        public string N17 { get; set; }
        public string N18 { get; set; }
        public string N19 { get; set; }
        public string N20 { get; set; }
        public string N21 { get; set; }
        public string N22 { get; set; }
        public string N23 { get; set; }
        public string N24 { get; set; }
        public string N25 { get; set; }
        public string N26 { get; set; }
        public string N27 { get; set; }
        public string N28 { get; set; }
        public string N29 { get; set; }
        public string N30 { get; set; }
        public string N31 { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> Cdate { get; set; }
    }
}
