//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_giaovien_lop
    {
        public int so { get; set; }
        public Nullable<decimal> so_giaovien { get; set; }
        public Nullable<int> so_namhoc_lop { get; set; }
        public string GhiChu { get; set; }
    }
}
