//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_sodiem
    {
        public decimal so { get; set; }
        public int so_hv { get; set; }
        public decimal so_mhlop { get; set; }
        public string hocky { get; set; }
        public Nullable<decimal> kt1 { get; set; }
        public Nullable<decimal> kt2 { get; set; }
        public Nullable<decimal> kt3 { get; set; }
        public Nullable<decimal> kt4 { get; set; }
        public Nullable<decimal> kt5 { get; set; }
        public Nullable<decimal> kt6 { get; set; }
        public Nullable<decimal> kt21 { get; set; }
        public Nullable<decimal> kt22 { get; set; }
        public Nullable<decimal> kt23 { get; set; }
        public Nullable<decimal> kt24 { get; set; }
        public Nullable<decimal> kt25 { get; set; }
        public Nullable<decimal> kt26 { get; set; }
        public Nullable<decimal> dl1 { get; set; }
        public Nullable<decimal> dl2 { get; set; }
        public Nullable<decimal> dl3 { get; set; }
        public Nullable<decimal> dln { get; set; }
        public string danhgia { get; set; }
        public string ma_users { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
    }
}
