//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_lophoc_dichvu
    {
        public int so { get; set; }
        public int so_dv { get; set; }
        public int so_namhoc_lop { get; set; }
        public string ghichu { get; set; }
    }
}
