//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_cackhoanthu
    {
        public int so { get; set; }
        public int so_namhoc { get; set; }
        public int so_coso { get; set; }
        public int so_hedaotao { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public string mota { get; set; }
        public string loai { get; set; }
        public string dvt { get; set; }
        public string ghichu { get; set; }
        public bool sudung { get; set; }
    }
}
