//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_giaovien
    {
        public int SO { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public string CHUCVU { get; set; }
        public string BOMON { get; set; }
        public string TRINHDO { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string HE { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public string GT { get; set; }
        public string QUOCTICH { get; set; }
        public string LOAI { get; set; }
        public string KIEMNHIEM { get; set; }
        public string GHICHU { get; set; }
        public bool SUDUNG { get; set; }
    }
}
