//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_insert
    {
        public int so { get; set; }
        public string ma { get; set; }
        public string hodem { get; set; }
        public string ten { get; set; }
        public string quoctich { get; set; }
        public Nullable<System.DateTime> sinhnhat { get; set; }
        public string noisinh { get; set; }
        public Nullable<System.DateTime> ngaynhaphoc { get; set; }
        public string phai { get; set; }
        public string dantoc { get; set; }
        public string tongiao { get; set; }
        public string email { get; set; }
        public string cccd { get; set; }
        public string dienthoai { get; set; }
        public Nullable<int> so_donvi { get; set; }
        public Nullable<int> so_namhoc { get; set; }
        public string khoi { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string userid { get; set; }
    }
}
