//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_khoi_namhoc
    {
        public decimal SO { get; set; }
        public decimal SO_KHOI { get; set; }
        public decimal SO_NAMHOC { get; set; }
        public int THANG { get; set; }
        public int TONGSOHS { get; set; }
        public int TONGSOHSMOI { get; set; }
        public int TONGSOHSRUTHOSO { get; set; }
        public string GHICHU { get; set; }
    }
}
