//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_namhoc
    {
        public decimal SO { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public int NAM { get; set; }
        public int LOAI { get; set; }
        public string GHICHU { get; set; }
        public Nullable<bool> SUDUNG { get; set; }
        public string SORT { get; set; }
    }
}
