//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_lop_delete
    {
        public int so { get; set; }
        public int so_donvi { get; set; }
        public int so_hv { get; set; }
        public int so_namhoc_lop { get; set; }
        public Nullable<decimal> so_namhoc { get; set; }
        public Nullable<int> so_khoi { get; set; }
        public Nullable<decimal> so_lophoc { get; set; }
        public string loai { get; set; }
        public Nullable<decimal> giamtru { get; set; }
        public string giamtrutext { get; set; }
        public Nullable<decimal> ptck { get; set; }
        public string lydock { get; set; }
        public Nullable<decimal> ptck1 { get; set; }
        public string lydock1 { get; set; }
        public Nullable<decimal> ptck2 { get; set; }
        public string lydock2 { get; set; }
        public Nullable<decimal> ptck3 { get; set; }
        public string lydock3 { get; set; }
        public Nullable<decimal> ptck4 { get; set; }
        public string lydock4 { get; set; }
        public Nullable<System.DateTime> ngayvaolop { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<System.DateTime> trangthaingay { get; set; }
        public string trangthailydo { get; set; }
        public string ghichu { get; set; }
        public bool dong1nam { get; set; }
        public bool dongta1nam { get; set; }
        public bool dongnt1nam { get; set; }
        public bool dongxe1nam { get; set; }
        public string stt { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string userid { get; set; }
    }
}
