//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_namhoclop_thoikhoabieu
    {
        public int so { get; set; }
        public Nullable<int> so_namhoc_lop { get; set; }
        public string ten { get; set; }
        public string hocky { get; set; }
        public Nullable<System.DateTime> tungay { get; set; }
        public Nullable<System.DateTime> denngay { get; set; }
        public string ghichu { get; set; }
    }
}
