//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_lop_dichvu_hocsinh
    {
        public int so { get; set; }
        public int so_hv { get; set; }
        public int so_lop_dv { get; set; }
        public Nullable<bool> codangky { get; set; }
        public string ghichu { get; set; }
        public Nullable<System.DateTime> mdate { get; set; }
    }
}
