//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_phieuthu_log
    {
        public decimal so { get; set; }
        public Nullable<int> so_hocsinh_lop { get; set; }
        public int so_donvi { get; set; }
        public int so_namhoc { get; set; }
        public string hocphan { get; set; }
        public string soct { get; set; }
        public System.DateTime ngayct { get; set; }
        public decimal so_hocsinh { get; set; }
        public Nullable<int> so_lophoc { get; set; }
        public string hoten { get; set; }
        public string diachi { get; set; }
        public string nguoinop { get; set; }
        public string nguoithu { get; set; }
        public decimal sotien { get; set; }
        public string loai { get; set; }
        public string diengiai { get; set; }
        public string httt { get; set; }
        public string nganhang { get; set; }
        public string ma_dtth { get; set; }
        public string ma_user { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<System.DateTime> deletedate { get; set; }
    }
}
