//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_donvi
    {
        public int so { get; set; }
        public string ma { get; set; }
        public string ten { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public int so_donvi { get; set; }
        public string ma_donvi { get; set; }
        public string ten_donvi { get; set; }
        public string truong { get; set; }
        public string sotk1 { get; set; }
        public string nganhang1 { get; set; }
        public string sotk2 { get; set; }
        public string nganhang2 { get; set; }
        public string sotk3 { get; set; }
        public string nganhang3 { get; set; }
        public Nullable<int> so_he { get; set; }
        public string ma_hdt { get; set; }
        public Nullable<int> so_coso { get; set; }
        public string ghichu { get; set; }
        public bool sudung { get; set; }
    }
}
