//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTPN
    {
        public int SO { get; set; }
        public string MA { get; set; }
        public string TEN { get; set; }
        public string TEN2 { get; set; }
        public string DCHI { get; set; }
        public string DT { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string MST { get; set; }
        public string CMNDDKKD { get; set; }
        public decimal NOTOIDA { get; set; }
        public Nullable<int> SO_QUOCGIA { get; set; }
        public Nullable<int> SO_TINH { get; set; }
        public Nullable<int> SO_LHDN { get; set; }
        public int SO_NGANHNGHEKD { get; set; }
        public int SO_TKCLTGNO { get; set; }
        public int SO_TKCLTGCO { get; set; }
        public string NGANHANG { get; set; }
        public string SOTAIKHOAN { get; set; }
        public string NGUOIDAIDIEN { get; set; }
        public string CHUCVU { get; set; }
        public string NGUOIMUAHANG { get; set; }
        public string DCHIGIAONHAN { get; set; }
        public int SO_TKMN { get; set; }
        public int SO_DTPNTH { get; set; }
        public string MANOIBO { get; set; }
        public int TINHTONKHOVOCHAI { get; set; }
        public int SONGAYTT { get; set; }
        public int SO_HOPNHAT { get; set; }
        public string CAPDAILY { get; set; }
        public decimal CKHAUPT { get; set; }
        public int SO_DTPN_CU { get; set; }
        public int SUDUNG { get; set; }
        public int READONLY { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string MA2 { get; set; }
        public string HOTENHS { get; set; }
        public string MALOP { get; set; }
    }
}
