//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTPN_CHITIETHOCVIEN
    {
        public int so { get; set; }
        public Nullable<int> so_dtpn { get; set; }
        public string ma { get; set; }
        public string ma2 { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public Nullable<bool> isEmployee { get; set; }
        public string danhxung { get; set; }
        public string hoten { get; set; }
        public string hodem { get; set; }
        public string ten { get; set; }
        public string nickname { get; set; }
        public string Quoctich { get; set; }
        public Nullable<System.DateTime> sinhnhat { get; set; }
        public string noisinh { get; set; }
        public Nullable<System.DateTime> ngaynhaphoc { get; set; }
        public string phai { get; set; }
        public string dantoc { get; set; }
        public string tongiao { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
        public string quan { get; set; }
        public string thanhpho { get; set; }
        public string sizedongphuc { get; set; }
        public string cmnd { get; set; }
        public string dienthoai { get; set; }
        public string noicap { get; set; }
        public Nullable<System.DateTime> ngaycap { get; set; }
        public string dctt_sonha { get; set; }
        public string dctt_tenduong { get; set; }
        public string dctt_to_khupho { get; set; }
        public string dctt_tinh_TP { get; set; }
        public string dctt_quan_huyen { get; set; }
        public string dctt_phuong_xa { get; set; }
        public string hktt { get; set; }
        public string dclh_sonha { get; set; }
        public string dclh_tenduong { get; set; }
        public string dclh_to_khupho { get; set; }
        public string dclh_tinh_tp { get; set; }
        public string dclh_quan_huyen { get; set; }
        public string dclh_phuong_xa { get; set; }
        public string anh_chi_em { get; set; }
        public string nhan_vien_tiep_thi { get; set; }
        public string cha_hoten { get; set; }
        public string cha_cmnd { get; set; }
        public Nullable<System.DateTime> cha_cmnd_ngaycap { get; set; }
        public string cha_cmnd_noicap { get; set; }
        public Nullable<int> cha_ngaysinh { get; set; }
        public string cha_nghenghiep { get; set; }
        public string cha_noilamviec { get; set; }
        public string cha_dienthoai { get; set; }
        public string me_hoten { get; set; }
        public string me_cmnd { get; set; }
        public Nullable<System.DateTime> me_cmnd_ngaycap { get; set; }
        public string me_cmnd_noicap { get; set; }
        public Nullable<int> me_ngaysinh { get; set; }
        public string me_nghenghiep { get; set; }
        public string me_noilamviec { get; set; }
        public string me_dienthoai { get; set; }
        public string chuyendentutruong { get; set; }
        public string tinhtrang { get; set; }
        public Nullable<System.DateTime> tinhtrang_ngay { get; set; }
        public string tinhtrang_lydo { get; set; }
        public Nullable<bool> thich_docsach { get; set; }
        public Nullable<bool> thich_nghekechuyen { get; set; }
        public Nullable<bool> thich_trochoivitinh { get; set; }
        public Nullable<bool> thich_xemtruyentranh { get; set; }
        public Nullable<bool> thich_nghehat { get; set; }
        public Nullable<bool> thich_mua { get; set; }
        public Nullable<bool> thich_xemtivi { get; set; }
        public Nullable<bool> thich_cahat { get; set; }
        public Nullable<bool> thich_chaynhay { get; set; }
        public string thich_mausac { get; set; }
        public string thich_thucan { get; set; }
        public string thich_nuocuong { get; set; }
        public string thich_cacmonhoc { get; set; }
        public string thich_khac { get; set; }
        public Nullable<bool> so_trachphat { get; set; }
        public Nullable<bool> so_lamang { get; set; }
        public Nullable<bool> so_bongtoi { get; set; }
        public Nullable<int> laconthu { get; set; }
        public Nullable<int> trongso { get; set; }
        public string ghichu { get; set; }
        public string nangkhieu { get; set; }
        public string macu { get; set; }
        public string khoi { get; set; }
        public string malop { get; set; }
        public Nullable<int> so_donvi { get; set; }
        public string userid { get; set; }
        public System.DateTime CDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public bool noitru { get; set; }
        public bool xeduadon { get; set; }
        public int chinhsach { get; set; }
        public Nullable<int> so_hocsinh { get; set; }
        public string hoten_cs { get; set; }
        public string quanhe_cs { get; set; }
        public string bophan_cs { get; set; }
    }
}
