//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCVIENLOP
    {
        public int SO { get; set; }
        public int SO_DTPN { get; set; }
        public int SO_LOP { get; set; }
        public int SO_DONVI { get; set; }
        public decimal HOCPHI { get; set; }
        public decimal CHIETKHAU { get; set; }
        public decimal SO_PVTHTG { get; set; }
        public string GHICHU { get; set; }
        public string MA_USERS { get; set; }
    }
}
