//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_DK_TIMKIEM
    {
        public int STT { get; set; }
        public string BAOCAO { get; set; }
        public string FORM { get; set; }
        public string MOTA { get; set; }
        public string FIELD { get; set; }
        public bool CHUAN { get; set; }
        public string FROMTABLE { get; set; }
        public string VALUETYPE { get; set; }
        public int WIDTHLBL { get; set; }
    }
}
