//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_DATAGRID_TITLE
    {
        public int DATAGRID_TITLE { get; set; }
        public string DATAGRID_NAME { get; set; }
        public string FORMNAME { get; set; }
        public string PARAMETER { get; set; }
        public bool CAPTIONVISIBLE { get; set; }
        public string CAPTIONTEXT { get; set; }
        public bool SORT { get; set; }
    }
}
