//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_DATAGRID
    {
        public int DATAGRID { get; set; }
        public int DATAGRID_TITLE { get; set; }
        public int STT { get; set; }
        public string MAPPINGNAME { get; set; }
        public string HEADERTEXT { get; set; }
        public int WIDTH { get; set; }
        public int ALIGNMENT { get; set; }
        public bool VISIBLE { get; set; }
        public bool READONLY { get; set; }
        public bool SEARCH { get; set; }
        public string FORMAT { get; set; }
        public string VALUETYPE { get; set; }
    }
}
