//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class student_db_allEntities : DbContext
    {
        public student_db_allEntities()
            : base("name=student_db_allEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aci_cackhoanthu> aci_cackhoanthu { get; set; }
        public virtual DbSet<aci_cackhoanthu_chitiet> aci_cackhoanthu_chitiet { get; set; }
        public virtual DbSet<aci_cackhoanthu_chitiet_donvi> aci_cackhoanthu_chitiet_donvi { get; set; }
        public virtual DbSet<aci_cackhoanthu_chitiet_thang> aci_cackhoanthu_chitiet_thang { get; set; }
        public virtual DbSet<aci_cackhoanthu_chitiet_xe> aci_cackhoanthu_chitiet_xe { get; set; }
        public virtual DbSet<aci_chinhsach> aci_chinhsach { get; set; }
        public virtual DbSet<aci_congno_dauky> aci_congno_dauky { get; set; }
        public virtual DbSet<aci_coso> aci_coso { get; set; }
        public virtual DbSet<aci_hocphi_namhoc_khoi> aci_hocphi_namhoc_khoi { get; set; }
        public virtual DbSet<aci_hocphi_namhoc_khoi_thang> aci_hocphi_namhoc_khoi_thang { get; set; }
        public virtual DbSet<aci_hocsinh_congno> aci_hocsinh_congno { get; set; }
        public virtual DbSet<aci_hocsinh_congno_thang> aci_hocsinh_congno_thang { get; set; }
        public virtual DbSet<aci_hocsinh_lop> aci_hocsinh_lop { get; set; }
        public virtual DbSet<aci_hocsinh_lop_cackhoanthu> aci_hocsinh_lop_cackhoanthu { get; set; }
        public virtual DbSet<aci_hocsinh_lop_cackhoanthu_thang> aci_hocsinh_lop_cackhoanthu_thang { get; set; }
        public virtual DbSet<aci_hocsinh_lop_cackhoanthumau> aci_hocsinh_lop_cackhoanthumau { get; set; }
        public virtual DbSet<aci_hocsinh_lop_congno_ketqua> aci_hocsinh_lop_congno_ketqua { get; set; }
        public virtual DbSet<aci_hocsinh_lop_diemdanhthang> aci_hocsinh_lop_diemdanhthang { get; set; }
        public virtual DbSet<aci_hocsinh_phieuthu> aci_hocsinh_phieuthu { get; set; }
        public virtual DbSet<aci_hocsinh_phieuthu_thang> aci_hocsinh_phieuthu_thang { get; set; }
        public virtual DbSet<aci_hocsinh_relationship> aci_hocsinh_relationship { get; set; }
        public virtual DbSet<aci_khoa_hocphan> aci_khoa_hocphan { get; set; }
        public virtual DbSet<aci_khoa_ky> aci_khoa_ky { get; set; }
        public virtual DbSet<aci_lophoc> aci_lophoc { get; set; }
        public virtual DbSet<aci_lophoc_monhoc> aci_lophoc_monhoc { get; set; }
        public virtual DbSet<aci_namhoc> aci_namhoc { get; set; }
        public virtual DbSet<aci_namhoc_lop> aci_namhoc_lop { get; set; }
        public virtual DbSet<aci_tinhtrang> aci_tinhtrang { get; set; }
        public virtual DbSet<DM_LOPHOC> DM_LOPHOC { get; set; }
        public virtual DbSet<DTPN> DTPNs { get; set; }
        public virtual DbSet<DTPN_CHITIETHOCVIEN> DTPN_CHITIETHOCVIEN { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<HOCVIENLOP> HOCVIENLOPs { get; set; }
        public virtual DbSet<HT_BAOCAO> HT_BAOCAO { get; set; }
        public virtual DbSet<HT_DATAGRID> HT_DATAGRID { get; set; }
        public virtual DbSet<HT_DATAGRID_TITLE> HT_DATAGRID_TITLE { get; set; }
        public virtual DbSet<HT_DK_TIMKIEM> HT_DK_TIMKIEM { get; set; }
        public virtual DbSet<PVTH> PVTHs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TRANGTHAI> TRANGTHAIs { get; set; }
        public virtual DbSet<aaalog> aaalogs { get; set; }
        public virtual DbSet<aci_cahoc> aci_cahoc { get; set; }
        public virtual DbSet<aci_congno_cantru_dauky> aci_congno_cantru_dauky { get; set; }
        public virtual DbSet<aci_dantoc> aci_dantoc { get; set; }
        public virtual DbSet<aci_dichvu> aci_dichvu { get; set; }
        public virtual DbSet<aci_donvi> aci_donvi { get; set; }
        public virtual DbSet<aci_giaovien> aci_giaovien { get; set; }
        public virtual DbSet<aci_giaovien_lop> aci_giaovien_lop { get; set; }
        public virtual DbSet<aci_hedaotao> aci_hedaotao { get; set; }
        public virtual DbSet<aci_hocphan> aci_hocphan { get; set; }
        public virtual DbSet<aci_hocsinh_cackhoanthu> aci_hocsinh_cackhoanthu { get; set; }
        public virtual DbSet<aci_hocsinh_cackhoanthumau> aci_hocsinh_cackhoanthumau { get; set; }
        public virtual DbSet<aci_hocsinh_insert> aci_hocsinh_insert { get; set; }
        public virtual DbSet<aci_hocsinh_log> aci_hocsinh_log { get; set; }
        public virtual DbSet<aci_hocsinh_lop_cackhoanthu_log> aci_hocsinh_lop_cackhoanthu_log { get; set; }
        public virtual DbSet<aci_hocsinh_lop_delete> aci_hocsinh_lop_delete { get; set; }
        public virtual DbSet<aci_hocsinh_lop_kqht> aci_hocsinh_lop_kqht { get; set; }
        public virtual DbSet<aci_hocsinh_phieuthu_ct> aci_hocsinh_phieuthu_ct { get; set; }
        public virtual DbSet<aci_hocsinh_phieuthu_log> aci_hocsinh_phieuthu_log { get; set; }
        public virtual DbSet<aci_hocsinh_update> aci_hocsinh_update { get; set; }
        public virtual DbSet<aci_kehoachdaotao> aci_kehoachdaotao { get; set; }
        public virtual DbSet<aci_khieunai> aci_khieunai { get; set; }
        public virtual DbSet<aci_khoi> aci_khoi { get; set; }
        public virtual DbSet<aci_khoi_namhoc> aci_khoi_namhoc { get; set; }
        public virtual DbSet<aci_ky> aci_ky { get; set; }
        public virtual DbSet<aci_loaihinh> aci_loaihinh { get; set; }
        public virtual DbSet<aci_lop_dichvu_hocsinh> aci_lop_dichvu_hocsinh { get; set; }
        public virtual DbSet<aci_lophoc_dichvu> aci_lophoc_dichvu { get; set; }
        public virtual DbSet<aci_monhoc> aci_monhoc { get; set; }
        public virtual DbSet<aci_namhoclop_thoikhoabieu> aci_namhoclop_thoikhoabieu { get; set; }
        public virtual DbSet<aci_noixulykhieunai> aci_noixulykhieunai { get; set; }
        public virtual DbSet<aci_phanloaikhieunai> aci_phanloaikhieunai { get; set; }
        public virtual DbSet<aci_phonghoc> aci_phonghoc { get; set; }
        public virtual DbSet<aci_phuongthucphanhoi> aci_phuongthucphanhoi { get; set; }
        public virtual DbSet<aci_quoctich> aci_quoctich { get; set; }
        public virtual DbSet<aci_sodiem> aci_sodiem { get; set; }
        public virtual DbSet<aci_thoikhoabieu> aci_thoikhoabieu { get; set; }
        public virtual DbSet<aci_tieudekhieunai> aci_tieudekhieunai { get; set; }
        public virtual DbSet<aci_tongiao> aci_tongiao { get; set; }
        public virtual DbSet<aci_truong> aci_truong { get; set; }
        public virtual DbSet<tab_congno_all> tab_congno_all { get; set; }
        public virtual DbSet<tab_congo_tonghop_2023> tab_congo_tonghop_2023 { get; set; }
        public virtual DbSet<tab_congo_tonghop_cuoinam> tab_congo_tonghop_cuoinam { get; set; }
        public virtual DbSet<tab_hocsinh_tmp> tab_hocsinh_tmp { get; set; }
        public virtual DbSet<Tab_IT> Tab_IT { get; set; }
        public virtual DbSet<TAB_SOPHIEU> TAB_SOPHIEU { get; set; }
        public virtual DbSet<tab_tmp> tab_tmp { get; set; }
        public virtual DbSet<tablename> tablenames { get; set; }
    }
}
