//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PVTH
    {
        public decimal SO { get; set; }
        public int SO_DONVI { get; set; }
        public string MA_LOAICT { get; set; }
        public string MA_PTNX { get; set; }
        public string SOCT { get; set; }
        public System.DateTime NGAYCT { get; set; }
        public int SO_KHO { get; set; }
        public Nullable<int> SO_KHO2 { get; set; }
        public decimal SO_DTPN { get; set; }
        public decimal SO_DTPN2 { get; set; }
        public decimal SO_DTTH { get; set; }
        public decimal SO_KMCP { get; set; }
        public int SO_NVPV { get; set; }
        public string HOTEN { get; set; }
        public string TENKHVAT2 { get; set; }
        public string DCHI2 { get; set; }
        public string CMND2 { get; set; }
        public int SO_TINH2 { get; set; }
        public string DGIAI { get; set; }
        public int SO_LOAITIEN { get; set; }
        public decimal TYGIA { get; set; }
        public string MAUSO { get; set; }
        public string SOSERI { get; set; }
        public int SO_LOAIHOADON { get; set; }
        public string SOHD { get; set; }
        public Nullable<System.DateTime> NGAYHD { get; set; }
        public string TENKHVAT { get; set; }
        public string DCHI { get; set; }
        public string MST { get; set; }
        public int SO_PTTTOAN { get; set; }
        public string MATHANG { get; set; }
        public decimal MUCTHUEVAT { get; set; }
        public decimal TIENTHUEVAT { get; set; }
        public decimal MUCTHUETTDB { get; set; }
        public decimal TIENTHUETTDB { get; set; }
        public decimal MUCCKHAU { get; set; }
        public decimal MUCCHIPHIHT { get; set; }
        public Nullable<int> SO_DINHKHOAN { get; set; }
        public Nullable<int> TK__CPKHVR { get; set; }
        public Nullable<System.DateTime> HANTT { get; set; }
        public decimal SO_HOPDONG { get; set; }
        public int NAM_HOPDONG { get; set; }
        public int SO_PHONGBAN { get; set; }
        public string SOLENH { get; set; }
        public string NGUOIRALENH { get; set; }
        public string VEVIEC { get; set; }
        public string MESX { get; set; }
        public int LAN { get; set; }
        public int SO_PTVC { get; set; }
        public string TEN_PTVC { get; set; }
        public int SO_PHIMUAHANG { get; set; }
        public decimal SO_PVTHCP { get; set; }
        public int CONGNO__NAM { get; set; }
        public string CONGNO__LOAIPHIEU { get; set; }
        public decimal CONGNO__SOPHIEU { get; set; }
        public string MA_PTNXNHAP { get; set; }
        public string MA_USERS { get; set; }
        public string NGUOINHANHANG { get; set; }
        public string DTHOAI { get; set; }
        public string GIAOTAIKHO { get; set; }
        public string HDGTGTDANHAN { get; set; }
        public int SO_CHINHANH { get; set; }
        public decimal SO_PVTH_CU { get; set; }
        public int READONLY { get; set; }
        public int FLAG { get; set; }
        public string GIO { get; set; }
        public string MA_TRANGTHAI { get; set; }
        public string LYDOGIAOHANG { get; set; }
        public Nullable<System.DateTime> HANGH { get; set; }
        public string GHICHU { get; set; }
        public string RefID { get; set; }
        public string ContactName { get; set; }
        public string AccountObjectName { get; set; }
        public string AccountObjectAddress { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
    }
}
