//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_congo_tonghop_2023
    {
        public int so_donvi { get; set; }
        public string hedt_ma { get; set; }
        public string khoi_ma { get; set; }
        public string lop_ma { get; set; }
        public int so_hocsinh { get; set; }
        public string ma { get; set; }
        public string ma2 { get; set; }
        public string hoten { get; set; }
        public Nullable<decimal> so_namhoc { get; set; }
        public Nullable<decimal> so_khoi { get; set; }
        public Nullable<decimal> DKCO_HP1 { get; set; }
        public Nullable<decimal> DKNO_HP1 { get; set; }
        public Nullable<decimal> DUNOCK_HP1 { get; set; }
        public Nullable<decimal> DUCOCK_HP1 { get; set; }
        public Nullable<decimal> DKCO_HP2 { get; set; }
        public Nullable<decimal> DKNO_HP2 { get; set; }
        public Nullable<decimal> DUNOCK_HP2 { get; set; }
        public Nullable<decimal> DUCOCK_HP2 { get; set; }
        public Nullable<decimal> DKNO_HP3 { get; set; }
        public Nullable<decimal> DKCO_HP3 { get; set; }
        public Nullable<decimal> DUNOCK_HP3 { get; set; }
        public Nullable<decimal> DUCOCK_HP3 { get; set; }
        public Nullable<decimal> DKNO_HP4 { get; set; }
        public Nullable<decimal> DKCO_HP4 { get; set; }
        public Nullable<decimal> DUNOCK_HP4 { get; set; }
        public Nullable<decimal> DUCOCK_HP4 { get; set; }
        public Nullable<decimal> DKNO_HP5 { get; set; }
        public Nullable<decimal> DKCO_HP5 { get; set; }
        public Nullable<decimal> DUNOCK_HP5 { get; set; }
        public Nullable<decimal> DUCOCK_HP5 { get; set; }
        public Nullable<decimal> DUNOCK { get; set; }
        public Nullable<decimal> DUCOCK { get; set; }
    }
}
