//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tablename
    {
        public string TABLE_NAME { get; set; }
        public string TABLE_TYPE { get; set; }
        public string REMARKS { get; set; }
        public string LOP { get; set; }
        public string COSO { get; set; }
    }
}
