//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Code
{
    using SchoolSMSVaschool.ConnectDB;
    using SchoolSMSVaschool.Model;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    public partial class aci_hocsinh_insert 
    {
        public int so { get; set; }
        public string ma { get; set; }
        public string hodem { get; set; }
        public string ten { get; set; }
        //public string quoctich { get; set; }
        public Nullable<System.DateTime> sinhnhat { get; set; }
        //public string noisinh { get; set; }
        //public Nullable<System.DateTime> ngaynhaphoc { get; set; }
        public string phai { get; set; }
        //public string dantoc { get; set; }
        //public string tongiao { get; set; }
        //public string email { get; set; }
        //public string cccd { get; set; }
        //public string dienthoai { get; set; }
        //public Nullable<int> so_donvi { get; set; }
        //public Nullable<int> so_namhoc { get; set; }
        //public string khoi { get; set; }
        //public Nullable<System.DateTime> ModifiedDate { get; set; }
        //public string userid { get; set; }

        public void Assign(aci_hocsinh_insert src)
        {
            so = src.so;
            ma = src.ma;
            ten = src.ten;
            sinhnhat = src.sinhnhat;
            phai = src.phai;

        }
    }
    public static class DataProvider3
    { 
        public static List<aci_hocsinh_insert> GetStudents()
        {
            if (HttpContext.Current.Session["Students"] == null)
            {
                // cấu trúc cơ bản 
                ConnectDatabase connect = new ConnectDatabase();
                List<aci_hocsinh_insert> listStudent = new List<aci_hocsinh_insert>();
                listStudent = connect.GetDataReader<aci_hocsinh_insert>("select * from Students");


                HttpContext.Current.Session["Students"] = listStudent;
                //HttpContext.Current.Session["Students"] = GenerateMenuStudent(); 
                var newlist = listStudent ;
            }


            return HttpContext.Current.Session["Students"] as List<aci_hocsinh_insert>;
        }
        static void UpdateMenuStudent(List<aci_hocsinh_insert> newlist)
        {
            
            HttpContext.Current.Session["Students"] = newlist;
        }

        private static readonly object lockObject = new object();
        public static void AddNewMenuStudent(aci_hocsinh_insert listStudent)
        {
            lock (lockObject)
            {
                List<aci_hocsinh_insert> StudentDB = GetStudents();
                listStudent.sinhnhat = DateTime.Now;
                listStudent.so = GetNextMenuStudentId();


                StudentDB.Add(listStudent);

                UpdateMenuStudent(StudentDB);
            }

        }
        public static void UpdateMenuStudent(aci_hocsinh_insert StudentDB)
        {
            List<aci_hocsinh_insert> StudentDBs = GetStudents();

            aci_hocsinh_insert existingMenuStudent = StudentDBs.Find(i => i.so == StudentDB.so);
            if (existingMenuStudent != null)
                existingMenuStudent.Assign(StudentDB);

            UpdateMenuStudent(StudentDBs);
        }
        public static void DeleteMenuStudents(List<long> ids)
        {
            List<aci_hocsinh_insert> StudentDBs = GetStudents();
            StudentDBs.RemoveAll(i => ids.Contains(i.so));
            UpdateMenuStudent(StudentDBs);
        }

        static List<aci_hocsinh_insert> GenerateMenuStudent()
        {
            List<aci_hocsinh_insert> MenuStudents = new List<aci_hocsinh_insert> {
             new aci_hocsinh_insert {
               so = 1, ma = "1" ,ten="Vu Duc Long" , phai ="Nam", sinhnhat = new DateTime(2000, 10, 17) 
             },
               
           

            };



            return MenuStudents;
        }
        internal static int GetNextMenuStudentId()
        {
            IEnumerable<int> MenuStudentsIds = GetStudents().Select(i => i.so);
            if (MenuStudentsIds.Count() > 0)
                return MenuStudentsIds.Max() + 1;
            else
                return 1;
        }
    }
}
