//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_hocsinh_log
    {
        public int id { get; set; }
        public Nullable<int> so { get; set; }
        public string ma_new { get; set; }
        public string ma_old { get; set; }
        public string hodem { get; set; }
        public string ten { get; set; }
        public string ma2_new { get; set; }
        public string ma2_old { get; set; }
        public Nullable<System.DateTime> ModifiedDate_old { get; set; }
        public Nullable<System.DateTime> ModifiedDate_new { get; set; }
        public string userid { get; set; }
        public string loai { get; set; }
    }
}
