//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class student_db_allEntities7 : DbContext
    {
        public student_db_allEntities7()
            : base("name=student_db_allEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aci_hocsinh_lop> aci_hocsinh_lop { get; set; }
        public virtual DbSet<aci_hocsinh_insert> aci_hocsinh_insert { get; set; }
        public virtual DbSet<aci_hocsinh_log> aci_hocsinh_log { get; set; }
    }
}
