//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSMSVaschool.Models.Student
{
    using System;
    using System.Collections.Generic;
    
    public partial class aci_lophoc_monhoc
    {
        public decimal so { get; set; }
        public Nullable<int> so_lophoc { get; set; }
        public int so_monhoc { get; set; }
        public int so_namhoc_lop { get; set; }
        public decimal heso { get; set; }
        public bool monthi { get; set; }
        public bool montn { get; set; }
        public int loaimonhoc { get; set; }
        public string ghichu { get; set; }
    }
}
